Suppress compiler warnings and fix Python bindings
ompl/ompl pull request #979
Opened 2023-01-23 22:10 UTC by zkingston

- Some small changes with uninitialized memory to suppress some huge boost graph warnings
- Marking includes as system to not report internal warnings

2023-02-12 22:54 UTC, mamoll requested changes
You should bump the minimum boost version required in CMakeLists.txt, README.md, and docs if you remove `external/boost/python`. Just matching the boost .deb version on the oldest supported version of Ubuntu is a reasonable choice.

2023-02-12 22:54 UTC, mamoll commented on src/ompl/control/planners/syclop/Syclop.h
> +                std::set<int> covGridCells = {0};
I think you want to create an empty set, not a singleton set with 0 as its element.
```suggestion
                std::set<int> covGridCells = {};
```

2023-02-12 22:54 UTC, mamoll commented on src/ompl/control/planners/syclop/Syclop.h
> +                const Region *source = {0};
```suggestion
                const Region *source{nullptr};
```

2023-02-12 22:54 UTC, mamoll commented on src/ompl/control/planners/syclop/Syclop.h
> +                const Region *target = {0};
```suggestion
                const Region *target{nullptr};
```

2023-02-12 22:54 UTC, mamoll commented on src/ompl/control/planners/syclop/Syclop.h
> +                double cost = {0};
```suggestion
                double cost = {0.};
```

2023-02-12 22:54 UTC, mamoll commented on src/ompl/control/planners/syclop/Syclop.h
> +                bool empty = {0};
```suggestion
                bool empty{false};
```

2023-02-13 17:38 UTC, zkingston commented
No, I'll restore external boost - that should be a separate pull.

2023-02-14 17:50 UTC, mamoll approved these changes

2023-02-14 17:52 UTC, merged